/*LA TABLA MENSAJERO*/
INSERT INTO TBL_MENSAJERO (NOMBRE_M, TELEFONO, DOCUMENTO_M) VALUES ("OSCAR LÓPEZ MESA", 3109007869, 1000999230);
INSERT INTO TBL_MENSAJERO (NOMBRE_M, TELEFONO, DOCUMENTO_M) VALUES ("VANESSA GÓMEZ ZAPATA", 3109301269, 1240999230);
INSERT INTO TBL_MENSAJERO (NOMBRE_M, TELEFONO, DOCUMENTO_M) VALUES ("MILORD ARANGO JARAMILLO", 3112907869, 1000534230);
INSERT INTO TBL_MENSAJERO (NOMBRE_M, TELEFONO, DOCUMENTO_M) VALUES ("LUIS GUERRA ORREGO", 3109005659, 1653654230);
INSERT INTO TBL_MENSAJERO (NOMBRE_M, TELEFONO, DOCUMENTO_M) VALUES ("MARÍA RODRIGUEZ OCAMPO", 3129007869, 1030999230);

/*LA TABLA IGLESIA*/
INSERT INTO TBL_IGLESIA (NOMBRE_I, MUNICIPIO, DIRECCION_I) VALUES ("GORETTI", "BELLO", "Cl 65 63 B 13");
INSERT INTO TBL_IGLESIA (NOMBRE_I, MUNICIPIO, DIRECCION_I) VALUES ("San Juan Apóstol", "Medellín", " Carrera 25 No. 1A Sur 155");
INSERT INTO TBL_IGLESIA (NOMBRE_I, MUNICIPIO, DIRECCION_I) VALUES ("San José", "Medellín", "Cra 43A #9-30");
INSERT INTO TBL_IGLESIA (NOMBRE_I, MUNICIPIO, DIRECCION_I) VALUES ("Divina Eucaristía", "Medellín", " Cl. 7 #35-56");
INSERT INTO TBL_IGLESIA (NOMBRE_I, MUNICIPIO, DIRECCION_I) VALUES ("San Juan de la Cruz", "Medellín", "Carrera 80A #28-145");

/*LA TABLA FORMA DE PAGO*/
INSERT INTO TBL_FORMA_PAGO (NOMBRE_FP, TOTAL_PAGAR, FECHA_PAGO) VALUES ("PAGO CONTRAENTREGA", 30000, "2008-05-15");
INSERT INTO TBL_FORMA_PAGO (NOMBRE_FP, TOTAL_PAGAR, FECHA_PAGO) VALUES ("CONSIGNACIÓN BANCARIA", 30000, "2018-04-15");
INSERT INTO TBL_FORMA_PAGO (NOMBRE_FP, TOTAL_PAGAR, FECHA_PAGO) VALUES ("TRANSFERENCIA ELECTRÓNICA", 15000, "2020-05-30");
INSERT INTO TBL_FORMA_PAGO (NOMBRE_FP, TOTAL_PAGAR, FECHA_PAGO) VALUES ("CONSIGNACIÓN BANCARIA", 15000, "2020-03-05");
INSERT INTO TBL_FORMA_PAGO (NOMBRE_FP, TOTAL_PAGAR, FECHA_PAGO) VALUES ("CONSIGNACIÓN BANCARIA", 15000, "2019-02-10");

/*LA TABLA COMPRADOR*/
INSERT INTO TBL_COMPRADOR (CORREO_C, CONTRASEÑA_C, NOMBRE_C, APELLIDOS_C, DOCUMENTO_C, TELEFONO_C, DIRECCION_C) VALUES ("oscarnr@gmail.com", 1234567, "Oscar", "Naranjo Restrepo", 1200340942, 3125467890, "Carrera 43 - 27 A56");
INSERT INTO TBL_COMPRADOR (CORREO_C, CONTRASEÑA_C, NOMBRE_C, APELLIDOS_C, DOCUMENTO_C, TELEFONO_C, DIRECCION_C) VALUES ("romeroluisapiedrahita@hotmail.com", 7654321, "Luisa", "Piedrahita Romero", 1000990230, 3110234506, "Carrera 2 B# 87 - 20");
INSERT INTO TBL_COMPRADOR (CORREO_C, CONTRASEÑA_C, NOMBRE_C, APELLIDOS_C, DOCUMENTO_C, TELEFONO_C, DIRECCION_C) VALUES ("escobarmazo@gmail.com", "mem12345", "Manuela", "Escobar Mazo", 1228300430, 3105768097, "Carrera 34 A-B 22");
INSERT INTO TBL_COMPRADOR (CORREO_C, CONTRASEÑA_C, NOMBRE_C, APELLIDOS_C, DOCUMENTO_C, TELEFONO_C, DIRECCION_C) VALUES ("milepatiño@gmail.com", "hola5432189", "Milena", "Patiño Martinez", 1030232323, 3112305562, "Carrera 98-21 D");
INSERT INTO TBL_COMPRADOR (CORREO_C, CONTRASEÑA_C, NOMBRE_C, APELLIDOS_C, DOCUMENTO_C, TELEFONO_C, DIRECCION_C) VALUES ("buztleongarcia@gmail.com", "lionlion", "León", "Buztamante Gárcia", 1200340456, 3100230562, "Carrera 10 C31");
/*PODRÍA TAN SOLO PONER * PARA NO PONER TODOS LOS ATRIBUTOS... PERO ME GUSTA ASÍ PARA SABER EN QUE ORDEN PONER LOS DATOS*/

/*LA TABLA SECRETARIA*/
INSERT INTO TBL_SECRETARIA (CORREO_S, CONTRASEÑA_S, NOMBRE_S, APELLIDOS_S, DOCUMENTO_S) VALUES ("marialuisa@gmail.com", 09877890, "María Luisa", "Urrego Correa", 1020008992);
INSERT INTO TBL_SECRETARIA (CORREO_S, CONTRASEÑA_S, NOMBRE_S, APELLIDOS_S, DOCUMENTO_S) VALUES ("toromonteroc@hotmail.com", "mcamilot123", "Camilo", "Montero Toro", 1990230034);
INSERT INTO TBL_SECRETARIA (CORREO_S, CONTRASEÑA_S, NOMBRE_S, APELLIDOS_S, DOCUMENTO_S) VALUES ("aristisabalreina@gmail.com", 90807060, "Reina", "Aristisabal Marín", 1300450002);
INSERT INTO TBL_SECRETARIA (CORREO_S, CONTRASEÑA_S, NOMBRE_S, APELLIDOS_S, DOCUMENTO_S) VALUES ("melissmora@gmail.com", "roth345roth", "Melissa", "Mora Roth", 1560009976);
INSERT INTO TBL_SECRETARIA (CORREO_S, CONTRASEÑA_S, NOMBRE_S, APELLIDOS_S, DOCUMENTO_S) VALUES ("josejose@hotmail.com", "jjj123jjj", "José", "Muñetón Castilla", 1009088976);

/*LA TABLA ENVÍO*/
INSERT INTO TBL_ENVIO (FECHA_ENVIO) VALUE ("2020-03-01");
INSERT INTO TBL_ENVIO (FECHA_ENVIO) VALUE ("2019-10-01");
INSERT INTO TBL_ENVIO (FECHA_ENVIO) VALUE ("2004-10-01");
INSERT INTO TBL_ENVIO (FECHA_ENVIO) VALUE ("2018-12-11");
INSERT INTO TBL_ENVIO (FECHA_ENVIO) VALUE ("2020-08-01");

/*LA TABLA PARTIDA*/
INSERT INTO TBL_PARTIDA (TIPO, FECHA_CREADA, COSTO) VALUES ("Bautismo", "2017-08-01", 15000);
INSERT INTO TBL_PARTIDA (TIPO, FECHA_CREADA, COSTO) VALUES ("Confirmación", "2012-05-02", 15000);
INSERT INTO TBL_PARTIDA (TIPO, FECHA_CREADA, COSTO) VALUES ("Matrimonio", "2004-03-03", 15000);
INSERT INTO TBL_PARTIDA (TIPO, FECHA_CREADA, COSTO) VALUES ("Defunción", "2009-04-04", 15000);
INSERT INTO TBL_PARTIDA (TIPO, FECHA_CREADA, COSTO) VALUES ("Bautismo", "2010-07-05", 15000);

SELECT * FROM TBL_SECRETARIA;

SELECT COUNT(*) FROM TBL_COMPRADOR;

SELECT MAX(NOMBRE_M) FROM TBL_MENSAJERO;

SELECT MIN(NOMBRE_I) AS MENOS_SOLICITADA FROM TBL_IGLESIA;

SELECT * FROM TBL_PARTIDA ORDER BY FECHA_CREADA DESC;

SELECT ID_ENVIO, FECHA_ENVIO FROM TBL_ENVIO WHERE ID_ENVIO<=15;

SELECT *, COUNT(*) AS CANT_FORMA_PAGO FROM TBL_FORMA_PAGO GROUP BY NOMBRE_FP;

SELECT * FROM TBL_COMPRADOR LIMIT 20;

SELECT * FROM TBL_COMPRADOR ORDER BY NOMBRE_C;

SELECT * FROM TBL_COMPRADOR, TBL_FORMA_PAGO;