CREATE DATABASE BACOMADE;

USE BACOMADE;

CREATE TABLE TBL_MENSAJERO(
ID_MENSAJERO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_M VARCHAR(40),
TELEFONO VARCHAR(10),
DOCUMENTO_M VARCHAR(10));

CREATE TABLE TBL_IGLESIA(
ID_IGLESIA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_I VARCHAR(30),
MUNICIPIO VARCHAR(20),
DIRECCION_I VARCHAR(30));

CREATE TABLE TBL_FORMA_PAGO(
ID_FORMA_P INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_FP VARCHAR(25),
TOTAL_PAGAR VARCHAR(6),
FECHA_PAGO DATETIME);

ALTER TABLE TBL_FORMA_PAGO MODIFY TOTAL_PAGAR DOUBLE;

CREATE TABLE TBL_COMPRADOR(
ID_COMPRADOR INT AUTO_INCREMENT PRIMARY KEY,
CORREO_C VARCHAR(40),
CONTRASEÑA_C VARCHAR(12),
NOMBRE_C VARCHAR(20),
APELLIDOS_C VARCHAR(30),
DOCUMENTO_C VARCHAR(10),
TELEFONO_C VARCHAR(10),
DIRECCION_C VARCHAR(30),
ID_F_P INT,
FOREIGN KEY (ID_F_P) REFERENCES TBL_FORMA_PAGO(ID_FORMA_P));

CREATE TABLE TBL_SECRETARIA(
ID_SECRETARIA INT AUTO_INCREMENT PRIMARY KEY,
CORREO_S VARCHAR(40),
CONTRASEÑA_S VARCHAR(12),
NOMBRE_S VARCHAR (20),
APELLIDOS_S VARCHAR (30),
DOCUMENTO_S VARCHAR(10),
ID_IGLE INT,
FOREIGN KEY (ID_IGLE) REFERENCES TBL_IGLESIA(ID_IGLESIA));

CREATE TABLE TBL_ENVIO(
ID_ENVIO INT AUTO_INCREMENT PRIMARY KEY,
FECHA_ENVIO DATETIME,
ID_MENS INT,
ID_FOR_P INT,
FOREIGN KEY (ID_MENS) REFERENCES TBL_MENSAJERO(ID_MENSAJERO),
FOREIGN KEY (ID_FOR_P) REFERENCES TBL_FORMA_PAGO(ID_FORMA_P));

CREATE TABLE TBL_PARTIDA(
ID_PARTIDA INT AUTO_INCREMENT PRIMARY KEY,
TIPO VARCHAR(12),
FECHA_CREADA DATETIME,
COSTO VARCHAR(6),
ID_ENV INT,
ID_IGL INT,
FOREIGN KEY (ID_IGL) REFERENCES TBL_IGLESIA(ID_IGLESIA),
FOREIGN KEY (ID_ENV) REFERENCES TBL_ENVIO(ID_ENVIO));

ALTER TABLE TBL_PARTIDA MODIFY COSTO DOUBLE;
